### ISSUE TITLE
Details about arguments

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#4]
Hello again! Thanks for answering all my previous questions!

I see there are many more command-line arguments and I assume the default ones are the best.

There are a few that I did not understand and did not see which part explains them.

1. has_run_num
2. objective_weights
3. check_unique_coeff

Can you help me understand what those are for?

**Comment by AIasd** [comment]
Hi @YuqiHuai ,

**has_run_num:** the total number of simulations to run before the algorithm ends.

**objective_weights:** the weights corresponding to each objective when estimating the fitness function.

**check_unique_coeff:** the thresholds (norm, th_2, th_1) used to count unique bugs. Currently, norm is always set to 0. For a given type of traffic  violation (collision or out-of-road), two violations caused by specific scenarios x and y are unique if at least th1 of the total number of changeable fields are different between the two. For a continuous field, the corresponding normalized values should be distinguishable by at least th2. (See section 4.1 in our paper for more details.)

**Comment by YuqiHuai** [comment]
Got it. Thank you so much for the explanations!
