### ISSUE TITLE
Possible cause of the collision in Apollo 6.0

### ISSUE THREAD

**Issue by ZiwenWan** [AIasd/ADFuzz#5]
Hi,

Thanks for the efforts in creating such great tool. The results are very impressive. I am wondering if there are more details about the collision discovered in Apollo 6.0? The finding is very interesting, but the root cause of this collision seems to be unclear (both on project website and in the paper).

Thanks a lot!

Best,

**Comment by AIasd** [comment]
Hi @ZiwenWan ,

Thank you for your question!

The root cause analysis of the found collisions is not the major goal of the current paper (which aims to maximize found collisions). However, we might later add more details into the revised version of the current paper. 

The found collisions can have different causes. Overall, most of them are either due to unstable object tracking and/or unstable object detection across frames. Consequently, the planning and control are influenced to make wrong decisions.

**Comment by ZiwenWan** [comment]
Hi @AIasd,
Thanks a lot for the reply!
I think this finding is really interesting. I was wondering is there any possibility that you could share more details of this collision (either scenario setup or ros/cyber bag would be extremely helpful)? 
Thanks!

**Comment by AIasd** [comment]
Hi @ZiwenWan ,

Due to some other commitments I currently have, I might not be able to provide these soon. However, I believe as long as you run the fuzzing process long enough you should be able to have seen some collisions. You can then consider to rerun the scenarios and gather the information you are interested in.

**Comment by ZiwenWan** [comment]
Hi @AIasd,

Thanks for the reply. I will have a try. Again, thanks for your efforts in creating such tool!

**Comment by AIasd** [comment]
Thanks for the great questions! Please feel free to open new issues if you have other questions.
